#!/bin/sh
#
# Start SNAP Connect instance
#

start() {
	echo -n "Starting FTP Server..."
	start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/ftpserver.pid --background --exec /usr/bin/python -- -m pyftpdlib.ftpserver -w -d /
	echo "OK"
}
stop() {
	echo -n "Stopping FTP Server..."
	start-stop-daemon --stop --quiet --pidfile /var/run/ftpserver.pid
	echo "OK"
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

