#!/bin/sh
#
# Start the network....
#

start() {
 	echo "Starting network..."
	/sbin/ifup -a
	/sbin/udhcpc -b
	if ifconfig | grep -A1 eth0 | grep inet
	then
		echo "IP Address was assigned by DHCP"
	else
		echo "Assigning default IP Address: 192.168.1.111"
		/sbin/ifconfig eth0 192.168.1.111 netmask 255.255.255.0
	fi
}	
stop() {
	echo -n "Stopping network..."
	/sbin/ifdown -a
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

