#!/bin/sh
#
# Start SNAP Connect instance
#

start() {
	/usr/bin/gpio9260 ?PB10 > /dev/null
	if [ $? -eq 0 ]; then 
		echo -n "Reseting GATE to default state..."
		start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/snapconnect.pid --background --exec /usr/bin/python /root/reset_gate.py
		echo "OK"
	else
		echo -n "Starting GATE..."
		start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/snapconnect.pid --background --exec /usr/bin/python /root/run_gate.py
		echo "OK"
	fi
}
stop() {
	echo -n "Stopping GATE..."
	start-stop-daemon --stop --quiet --pidfile /var/run/snapconnect.pid
	echo "OK"
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

